<?php
$_configHelper = Mage::helper('searchautocomplete/config');
$_product      = $this->getItem();
$helpImg = $this->helper('infortis/image');
$imgWidth = 295;
$imgHeight = 295;
$site_base_url = "http://" . $_SERVER["SERVER_NAME"];
?>
<li data-url="<?php echo $_product->getProductUrl() ?>">
    <?php if ($_configHelper->isShowImage()): ?>
    <div class="searchautocomlete-image">
        <img src="<?php echo $helpImg->getImg($_product, 0, 0, 'thumbnail'); ?>" width="<?php echo $_configHelper->getImageWidth() ?>px"/>
    </div>
    <?php endif ?>

    <a class="name highlight" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>

    <?php if ($_configHelper->isShowRating()): ?>
        <?php $_reviewSummary = $_configHelper->getReviewSummary($_product->getId()); ?>
        <?php if ($_reviewSummary->getReviewsCount() > 0) : ?>
        <div class="ratings">
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $_reviewSummary->getRatingSummary() ?>%"></div>
            </div>
            <span class="reviews"><?php echo $_reviewSummary->getReviewsCount() ?> Review(s)</span>
        </div>
        <?php endif ?>
    <?php endif ?>

    <?php if ($_configHelper->isShowShortDescription()): ?>
        <div class="highlight">
        <?php echo Mage::helper('core/string')->truncate(strip_tags($_product->getShortDescription()), $_configHelper->getShortDescriptionLen()) ?>
        </div>
    <?php endif ?>

    <?php if($_configHelper->isShowArtistName()): ?>
        <div class="highlight">
        <?php echo "<br/>Created by " . "<a href=" . $site_base_url . '/artists/' . str_replace(" ", "-", strtolower($_product->getUdfArtistName())) . ">" . $_product->getUdfArtistName() . "</a>" . ". <br />"; ?>
        </div>
    <?php endif ?>


    <?php if ($_configHelper->isShowPrice()): ?>
        <?php //echo $this->getPriceHtml($_product, false) ?>
        <?php echo $this->getPrice($_product); ?>

    <?php endif ?>
</li>