<?php if ($solutions = $this->getSolutions()): ?>

	<h1>Springbot encountered a problem</h1>
	<p>
		Don't worry! We can help with any problems you may have. Sometimes
		<a href="<?php echo $this->getUrl('bmbleb/adminhtml_index/auth') ?>">re-logging into Springbot</a> will fix any
		issues you may be having. If the problem persists please email our support team:
		<a href="mailto:support@springbot.com">support@springbot.com</a>.
	</p>

	<div class="grid">
		<table class="data" cellspacing="0">
			<thead>
			<tr class="headings">
				<th class="no-link"><span class="nobr">Problem</span></th>
				<th class="no-link"><span class="nobr">Possible solution</span></th>
			</tr>
			</thead>
			<tbody>


			<?php foreach ($solutions as $problem): ?>

				<tr>
					<td class="a-left">
						<strong><?php echo $problem['problem'] ?></strong>
					</td>

					<td class="a-left">
						<?php echo $problem['solution'] ?>
					</td>

				</tr>

			<?php endforeach ?>


			</tbody>
		</table>

	</div>
<?php endif ?>

