<div class="content-header">
	<h3>Help</h3>
</div>

<div id="help-screen-wrap">
	<div class="col-one">
		<script type="text/javascript" charset="utf-8">
			var is_ssl = ("https:" == document.location.protocol);
			var asset_host = is_ssl ? "https://s3.amazonaws.com/getsatisfaction.com/" : "http://s3.amazonaws.com/getsatisfaction.com/";
			document.write(unescape("%3Cscript src='" + asset_host + "javascripts/feedback-v2.js' type='text/javascript'%3E%3C/script%3E"));
		</script>
		<script type="text/javascript" charset="utf-8">
			var feedback_widget_options = {};
			feedback_widget_options.display = "inline";
			feedback_widget_options.company = "bmbleb";
			feedback_widget_options.style = "question";
			var feedback_widget = new GSFN.feedback_widget(feedback_widget_options);
		</script>
	</div>
	<div class="col-two">
		<div id='gsfn_search_widget'>
	    	<h3>Search</h3>
			<div class='gsfn_content'>
				<form accept-charset='utf-8' action='https://getsatisfaction.com/bmbleb' id='gsfn_search_form' method='get' onsubmit='gsfn_search(this); return false;'>
				<div>
					<input name='style' type='hidden' value='' />
					<input name='limit' type='hidden' value='10' />
					<input name='utm_medium' type='hidden' value='widget_search' />
					<input name='utm_source' type='hidden' value='widget_bmbleb' />
					<input name='callback' type='hidden' value='gsfnResultsCallback' />
					<input name='format' type='hidden' value='widget' />
					<label class='gsfn_label' for='gsfn_search_query'>Ask a question, share an idea, or report a problem.</label>
					<input id='gsfn_search_query' maxlength='120' name='query' type='text' value='' />
					<input id='continue' type='submit' value='Continue' />
				</div>
				</form>
				<div id='gsfn_search_results' style='height: auto;'></div>
			</div>
		</div>
		<script src="https://getsatisfaction.com/bmbleb/widgets/javascripts/3081adb659/widgets.js" type="text/javascript"></script>
	</div>
</div>


