<style>
#welcome-message{
    padding: 15px;
}
</style>
<a id="s3_result_light_box" class="fancybox" href="#s3_message"></a>

<div id="s3_message" style="width:400px; display: none;">
    <div id="welcome-message">
        <h2>Welcome Message</h2>
        <h3>Subtitle</h3>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
        <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
        <p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
        <p>It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
    </div>
</div>
<script>
    var jQuery = jQuery.noConflict();
    
    jQuery(document).ready(function(){
        
        jQuery("#s3_result_light_box").fancybox({
            'content':jQuery("#s3_message").html()
        });

        jQuery("#s3_result_light_box").trigger("click");
        
    });
</script>