<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * Create account form template
 *
 * @see app/design/frontend/base/default/template/customer/form/register.phtml
 */
/** @var $this Mage_Customer_Block_Form_Register */
?>
<div class="business-account-create">
    
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <h2><?php echo $this->__('Create A Business Account') ?></h2>
    <div class="continuous_divider_line"></div>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate" class="form well">
	    		
	    		<fieldset id="personal_information" class="control-group error">

		        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
                        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
                        <input type="hidden" name="customer-type" value="pro" />
	            				   
	                
	                <div class="fields">
	                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
	                </div>
	                
	                <div class="control-group" id="email_address_control_group">
	                   
	                    <div class="button">
	                        <input placeholder="<?php echo $this->__('Email Address') ?>" type="text" name="email" id="email_address" value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
	                        
	                        <!-- Customer group -->
	                        <div id="customer_registration_group" class="input-box">
								<label id="customer_group_id" for="group_id">
									<?php echo $this->__('Group') ?>
								</label>

								<br/>
								
								<select name="group_id" id="group_id" title="<?php echo $this->__('Group') ?>" class="validate-group required-entry input-text" />
								
									<?php $groups = Mage::helper('customer')->getGroups()->toOptionArray(); ?>
									<?php foreach($groups as $group){ ?>
										<option value="<?php print $group['value'] ?>"><?php print $group['label'] ?></option>
									<?php } ?>
								</select>
							</div>

							<!-- Twitter account -->
	                        <div class="input-box" id="twitter_account_fields">
								<label id="customer_twitter_account" for="twitter_account"><?php echo $this->__('Twitter Account') ?>
								</label>

								<br/>
								
								<input placeholder="<?php echo $this->__('Twitter Account') ?>" type="text" name="twitter_account" id="twitter_account" value="" title="" />
							</div>

	                    </div>
	                </div>
	                
	                <?php if ($this->isNewsletterEnabled()): ?>
	                
	                <div class="control-group" id="newsletter_control_group">
		                <div class="controls">
		                	<label for="is_subscribed" class="checkbox">
		                        <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
		                    	<?php echo $this->__('Sign Up for Newsletter') ?>
	                    	</label>
		                </div>
	                </div>
	                
	                <?php endif ?>
	        	
	        	</div>
						    
			<div class="span3">
			    
					<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
		            <?php if ($_dob->isEnabled()): ?>
		                <?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?>
		            <?php endif ?>
		            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
		            <?php if ($_taxvat->isEnabled()): ?>
		                <?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?>
		            <?php endif ?>
		            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
		            <?php if ($_gender->isEnabled()): ?>
		                <?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?>
		            <?php endif ?>

				    <?php if($this->getShowAddressFields()): ?>
				        <div class="fieldset">
				            <input type="hidden" name="create_address" value="1" />
				            
				            <div class="form-list">
				                <div class="fields">
				                    <div class="field">
				                        <label for="company"><?php echo $this->__('Company') ?></label>
				                        <div class="input-box">
				                            <input type="text" name="company" id="company" value="<?php echo $this->htmlEscape($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" />
				                        </div>
				                    </div>
				                    <div class="field">
				                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
				                        <div class="button">
				                            <input type="text" name="telephone" id="telephone" value="<?php echo $this->htmlEscape($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry" />
				                        </div>
				                    </div>
				                </div>
				                <div class="wide">
				                    <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
				                    <div class="button">
				                        <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text required-entry" />
				                    </div>
				                </div>
				            <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
				                <div class="wide">
				                    <div class="button">
				                        <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i?>" class="input-text" />
				                    </div>
				                </div>
				            <?php endfor ?>
				                <div class="fields">
				                    <div class="field">
				                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
				                        <div class="input-box">
				                            <input type="text" name="city" value="<?php echo $this->htmlEscape($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text required-entry" id="city" />
				                        </div>
				                    </div>
				                    <div class="field">
				                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
				                        <div class="input-box">
				                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
				                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
				                            </select>
				                            <script type="text/javascript">
				                            //<![CDATA[
				                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
				                            //]]>
				                            </script>
				                            <input type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
				                        </div>
				                    </div>
				                </div>
				                <div class="fields">
				                    <div class="field">
				                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
				                        <div class="input-box">
				                            <input type="text" name="postcode" value="<?php echo $this->htmlEscape($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international required-entry" />
				                        </div>
				                    </div>
				                    <div class="field">
				                        <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
				                        <div class="input-box">
				                            <?php echo $this->getCountryHtmlSelect() ?>
				                        </div>
				                    </div>
				                </div>
				            </div>
				            <input type="hidden" name="default_billing" value="1" />
				            <input type="hidden" name="default_shipping" value="1" />
				        </div>
				    <?php endif; ?>
			   
			</fieldset>
    	</div>

            
        <fieldset id="pro_login_information">
            
                    <div class="control-group error">
                        <div class="button">
                            <input placeholder="<?php echo $this->__('Password') ?>" value="Password" type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="control-group error">
                        <div class="button">
                            <input placeholder="<?php echo $this->__('Confirm Password') ?>" value="Confirm Password" type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
        </fieldset>
				    
   
    <p class="help-block"><?php echo $this->__('* Required Fields') ?></p>
        
        <div id="pro_create_account_submit_area">
            
            <button id="pro_create_account_submit_button" type="submit" title="<?php echo $this->__('Create account') ?>" class="btn btn-large btn-primary"><span><span><?php echo $this->__('CREATE ACCOUNT') ?></span></span></button>
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small class="icon-backward"></small><?php echo $this->__('Back') ?></a></p>
            
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
   
    </form>
    
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>

</div>
