<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * Create account form template
 *
 * @see app/design/frontend/base/default/template/customer/form/register.phtml
 */
/** @var $this Mage_Customer_Block_Form_Register */
?>
<div class="business-account-create">

    <?php echo $this->getChildHtml('form_fields_before') ?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <h2><?php echo $this->__('Create A Business Account') ?></h2>
    <div class="continuous_divider_line"></div>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate" class="form well">

        <fieldset id="personal_information" class="control-group">

            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <input type="hidden" name="customer-type" value="pro" />

            <ul class="form-list">
                <li class="fields">
                    <div class="fields">
                        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                    </div>
                </li>
                <li class="fields">
                    <label for="email" class="required">
                        <em>*</em>
                        Email
                    </label>
                    <div class="input-box">
                        <input placeholder="<?php echo $this->__('Email Address') ?>" type="text" name="email" id="email_address" value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
                <li class="fields">
                    <label id="customer_twitter_account" for="twitter_account"><?php echo $this->__('Twitter Account') ?>
                    </label>
                    <div class="input-box">
                    <input class="input-text validate-email required-entry" placeholder="<?php echo $this->__('Twitter Account') ?>" type="text" name="twitter_account" id="twitter_account" value="" title="" />
                    </div>
                </li>
                <li class="fields">
                    <?php if ($this->isNewsletterEnabled()): ?>

                        <div class="control-group" id="newsletter_control_group">
                            <div class="controls">
                                <label for="is_subscribed" class="checkbox">
                                    <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if ($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                                    <?php echo $this->__('Sign Up for Newsletter') ?>
                                </label>
                            </div>
                        </div>

                    <?php endif ?>
                </li>
                <li class="fields">

                    <div class="control-group error">
                        <div class="button">
                            <input placeholder="<?php echo $this->__('Password') ?>" value="Password" type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>

                </li>
                <li class="fields">
                    <div class="control-group error">
                        <div class="button">
                            <input placeholder="<?php echo $this->__('Confirm Password') ?>" value="Confirm Password" type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>

                    <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                </li>
            </ul>


            <p class="required t-left">
                <?php echo $this->__('* Required Fields') ?>
            </p>
            
            <div id="pro_create_account_submit_area">

                <button id="pro_create_account_submit_button" type="submit" title="<?php echo $this->__('Create account') ?>" class="button"><span><span><?php echo $this->__('CREATE ACCOUNT') ?></span></span></button>
                

            </div>
            <!--<br/>
            <p class="f-left">
                <a href="<?php //echo $this->escapeUrl($this->getBackUrl()) ?>">
                    <small class="icon-backward"></small>
                    <?php //echo $this->__('Back') ?>
                </a>
            </p>-->
            <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
                <input name="context" type="hidden" value="checkout" />
            <?php endif; ?>

    </form>
</div>

<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
<?php if ($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
<?php endif; ?>
    //]]>
</script>

</div>
