<?php
    $list = $this->getList();
    $index = array_keys($list);
?>
<div class="index-container">
    <ul id="navindex">
        <?php foreach ($index as $letter): ?>
            <li><a href="#"><?php echo $letter?></a></li>
        <?php endforeach;?>
    </ul>
</div>
<div class="artist-list">
<?php foreach($list as $key => $artists):?>
    <h4  id="index_<?php echo $key?>"><?php echo $key?></h4>
    <ul class="columns-list">
        <?php foreach($artists as $artist): ?>
            <li><a href="<?php echo $artist->getUrl()?>"><?php echo $artist->getName(),"&nbsp;(",$artist->getProductCount(),")" ?></a></li>
        <?php endforeach;?>
    </ul>
<?php endforeach;?>
</div>
<script>
    jQuery("#navindex a").click(function(){
       var letter = jQuery(this).text().replace(/([;&,\.\+\*\~':"\!\^#$%@\[\]\(\)=>\|])/g, '\\$1');;
        jQuery('html, body').animate({
            scrollTop: jQuery("#index_"+letter).offset().top
        }, 1500,'easeOutQuart');
    });
</script>