<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php
	$_helper = $this->helper('catalog/output');
	$_product = $this->getProduct();
	$theme = $this->helper('ultimo');

	//CSS classes based on product type
	$productTypeId = $_product->getTypeId();
	$productTypeClasses = '';
	if ($productTypeId === 'grouped') {
		$productTypeClasses .= ' is-type-grouped';
	}
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>




<!-- New code -->

<div id="product_view_container">

<?php $site_base_url = "http://" . $_SERVER["SERVER_NAME"]; ?>

<?php

	function endsWith( $str, $sub ) 
	{
	   return ( substr( $str, strlen( $str ) - strlen( $sub ) ) === $sub );
	}
	

	function get_first_number_index($text)
	{
	    preg_match('/^\D*(?=\d)/', $text, $m);
	    return strlen($m[0]);
	}

	function compute_size_initial($size_ui)
	{
		if ($size_ui < 40) 
			return "xs";

		if ($size_ui >= 40 and $size_ui < 50)
			return "s";

		if ($size_ui >= 50 and $size_ui < 60)
			return "m";

		if ($size_ui >= 60 and $size_ui < 70)
			return "l";

		if ($size_ui >= 70)
			return "xl";

		return "l";
	}
?>

<?php
	
	$popularity = $this->getProduct()->getPopularity();
	$this->getProduct()->setPopularity($popularity + 1)->save();

	$description = $_product->getName() .  " was created by " . "<a href=" . $site_base_url . '/artists/' . str_replace(" ","-", strtolower($_product->getUdfArtistName())) . ">" . $_product->getUdfArtistName() . "</a>" . ". <br />";

	$orientation = strtolower($_product->getAttributeText('udf_orientation'));

	// Show Canvas as material only when allowed
	$canvas_available = $_product->getUdfCanvas();
	$poster_available = $_product->getUdfPoster();
	$paper_available = $_product->getUdfPhotoPaper();

	// Stock information
	$is_in_stock = 0;
	$stockItem = $_product->getStockItem();
	if ($stockItem->getIsInStock())
	{
		$is_in_stock = 1;
	}
	else
	{
		$is_in_stock = 0;
	}

	echo "<div class='is_in_stock'>" . $is_in_stock . "</div>";

?>

<div id="final_product_image_background">

	<?php 

		$original_sku = $_product->getSku();
		$image_file_name = "";

		if ( endsWith($original_sku, "DG") )
		{
			$dg_suffix_index = strrpos($original_sku, "DG");
			$image_file_name = substr_replace($original_sku, "", $dg_suffix_index, 2) . ".jpg";
		}
		else
		{
			$image_file_name = $original_sku . ".jpg";
		}
		
		$one_corner_flag = 0;

		$thumbnail_image_base_url = "http://d3odr912zwpuhm.cloudfront.net/thumbnail_images/";
		$small_image_base_url = "http://d3odr912zwpuhm.cloudfront.net/small_images/";
		$large_image_base_url = "http://d3odr912zwpuhm.cloudfront.net/large_images/";
		
		$thumbnail_image_file_url = $thumbnail_image_base_url . $image_file_name;
		$small_image_file_url = $small_image_base_url . $image_file_name;
		$large_image_file_url = $large_image_base_url . $image_file_name;


		$framing_profile_url = "http://d3odr912zwpuhm.cloudfront.net/icons/framing_profiles/";
		$framing_corner_url = "http://d3odr912zwpuhm.cloudfront.net/icons/framing_corners/";


		// User uploaded image
		if ( isset($_POST['s3file']) )
		{
			$thumbnail_image_file_url = $_POST['s3file'];
			$small_image_file_url = $_POST['s3file'];
			$large_image_file_url = $_POST['s3file'];
		}

		echo "<div class='image_url'>" . $thumbnail_image_file_url . "</div>";

	?>

	
	<a href="<?php echo $large_image_file_url; ?>" rel="prettyPhoto" title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>, by <?php echo $_product->getUdfArtistName() ?>.">

		<div id="jcanvas_frame">

			<canvas id="corner_top_left" width="40" height="40" class="jcanvas_corner"></canvas>
			<canvas id="corner_top_right" width="40" height="40" class="jcanvas_corner"></canvas>
			<canvas id="corner_bottom_left" width="40" height="40" class="jcanvas_corner"></canvas>
			<canvas id="corner_bottom_right" width="40" height="40" class="jcanvas_corner"></canvas>

			<canvas id="edge_top" width="574" height="40" class="jcanvas_edge"></canvas>
			<canvas id="edge_left" height="574" width="40" class="jcanvas_edge"></canvas>
			<canvas id="edge_bottom" width="574" height="40" class="jcanvas_edge"></canvas>
			<canvas id="edge_right" height="574" width="40" class="jcanvas_edge"></canvas>

		</div>

		<div id="jcanvas_mats">
			
		</div>

		<div id="final_product_image" class="custom_option_viewport" style="background-image: url('<?php echo $small_image_file_url; ?>');">

			<div id="load_icon">
			</div>
			
		</div>
	</a>
	
</div>

<div id="hide_button">
	<div id="hide_down_arrow">
	
	</div>

	Hide
</div>

<div id="color_switch">
	<?php
		$color_set = array("#ffffff", "#f1efdc", "#fdf8de", "#f8ecc6","#faeddc", "#f5e7dc", "#fbebcf", "#ffe8a4", "#f6d9ad", "#f3c585", "#f3c589", "#7a4f3e", "#fbf7ec", "#e0d7c6", "#e1cead", "#b48b75", "#4c2625", "#6b6a6f", "#fdf0e7", "#d1797c", "#b2463a", "#c7a5be", "#493371", "#7086ab", "#ebf4f3", "#c4dae7", "#c2dbd8", "#98977b", "#d8e6b3", "#5fadaf");
		
		foreach ($color_set as $color) 
		{
			//echo "<div id='" . $color . "' class='color'></div>";
			echo "<div class='color' style='background-color: " . $color . "'></div>";
		}
	?>	
</div>

<div id="room_switch">
	<?php
		$dir =  getcwd() . '/media/rooms';
		//$dir = 'https://s3.amazonaws.com/topart_images/rooms/';

		$room_set = array();
		
		// Open a known directory, and proceed to read its contents
		if (is_dir($dir)) 
		{
			if ($dh = opendir($dir)) 
			{
				while (($file = readdir($dh)) !== false) 
				{
					$path_parts = pathinfo($dir . $file);
					$file_type = $path_parts['extension'];
					
					if ($file_type == "png" || $file_type == "jpg" || $file_type == "jpeg")
						array_push($room_set, $file);
				}
				closedir($dh);

				sort($room_set);
			}
		}
		
		$image_dir = $site_base_url . "/media/rooms/";
		
		foreach ($room_set as $room) 
		{
			echo "<img class='room_thumbnail' src='" . $image_dir . $room . "' />";
		}
		
	?>
</div>

<div id="details_switch">
	
	<div id="text">
		<?php echo $description; ?>
	</div>

	<?php

    	$udf_specpaper = $_product->getAttributeText('udf_specpaper');
    	$udf_foil = $_product->getAttributeText('udf_foil');
    	$udf_metallic_ink = $_product->getAttributeText('udf_metallic_ink');
    	$udf_embellished = $_product->getAttributeText('udf_embellished');
    	$udf_limited = $_product->getAttributeText('udf_limited');
    	$poster_size = $_product->getUdfImageSizeIn();

    	$special_features = "";

    	if ($udf_specpaper == "Yes")
    	{
    		$special_features = $special_features . "<div class='special_feature'><span class='bold'>Special Paper</span> - Fine Art Paper is specifically selected to enhance the image.</div>";
    	}

    	if ($udf_foil == "Yes")
    	{
    		$special_features = $special_features . "<div class='special_feature'><span class='bold'>Foil</span> - The addition of Metallic gold foil creates a subtle but dramatic visual effect.</div>";
    	}

    	if ($udf_metallic_ink == "Yes")
    	{
    		$special_features = $special_features . "<div class='special_feature'><span class='bold'>Metallic Inks</span> - Metallic Inks duplicate effects in the original painting, and enhance the image.</div>";
    	}

    	if ($udf_limited == "Yes")
    	{
    		$special_features = $special_features . "<div class='special_feature'><span class='bold'>Limited Edition</span> - Our Limited Edition pieces are hand signed, numbered and rare.</div>";
    	}

    ?>

	<div id="features">
		<?php echo $special_features; ?>
	</div>

	<div class="poster_size">
		<?php echo $poster_size; ?>
	</div>

</div>


<div id="options_sequence">

	<div id="option_one">1.</div>
	<div id="option_two">2.</div>
	<div id="option_three">3.</div>

</div>

<div id="product_image_functions">

	<a id="full_screen" class="function_icon">
		<div class="product_function_text">Full screen</div>
	</a>
	
	<a id="zoom_in" class="function_icon">
		<div class="product_function_text">Zoom in</div>
	</a>
	
	<a id="wall_color" class="function_icon">
		<div class="product_function_text">Wall color</div>
	</a>
	
	<a id="rooms" class="function_icon">
		<div class="product_function_text">Rooms</div>
	</a>

	<a id="reset" class="function_icon">
		<div class="product_function_text">Reset</div>
	</a>
	
	<a id="details" class="function_icon">
		<div class="product_function_text">Details</div>
	</a>
	
</div>

<!-- End of new code -->










<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">

    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

    	<?php echo $this->getBlockHtml('formkey'); ?>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>
        
    	<?php
			//Product collaterals
			$section = array();
			
			//Related products. $section['related'] is set only if related products (or replacement) exist
			$replaceRelated = $theme->getCfg('product_page/replace_related');
			if ($replaceRelated == 1) //don't replace with static block
			{
				if ($tmpHtml = trim($this->getChildHtml('catalog.product.related')))
					$section['related'] = $tmpHtml;
				//$section['related'] = trim($this->getChildHtml('catalog.product.related'));
			}
			elseif ($replaceRelated == 2) //if related is empty, replace with static block
			{
				if ($tmpHtml = trim($this->getChildHtml('catalog.product.related')))
					$section['related'] = $tmpHtml;
				else //related empty
					if ($tmpHtml = $this->getChildHtml('block_product_replace_related'))
						$section['related'] = '<div class="block_product_replace_related">'. $tmpHtml .'</div>';
			}
			elseif ($replaceRelated == 3) //replace with static block
			{
				if ($tmpHtml = $this->getChildHtml('block_product_replace_related'))
					$section['related'] = '<div class="block_product_replace_related">'. $tmpHtml .'</div>';
			}
	
			//Up-sell products. $section['upsell'] is set only if up-sell products (or replacement) exist
			$replaceUpsell = $theme->getCfg('product_page/replace_upsell');
			if ($replaceUpsell == 1) //don't replace with static block
			{
				if ($tmpHtml = trim($this->getChildHtml('upsell_products')))
					$section['upsell'] = $tmpHtml;
				//$section['upsell'] = $this->getChildHtml('upsell_products');
			}
			elseif ($replaceUpsell == 2) //if upsell is empty, replace with static block
			{
				if ($tmpHtml = trim($this->getChildHtml('upsell_products')))
					$section['upsell'] = $tmpHtml;
				else //upsell empty
					if ($tmpHtml = $this->getChildHtml('block_product_replace_upsell'))
						$section['upsell'] = '<div class="block_product_replace_upsell">'. $tmpHtml .'</div>';
			}
			elseif ($replaceUpsell == 3) //replace with static block
			{
				if ($tmpHtml = $this->getChildHtml('block_product_replace_upsell'))
					$section['upsell'] = '<div class="block_product_replace_upsell">'. $tmpHtml .'</div>';
			}
			
			
			
			//Assign related products to selected position
			if (isset($section['related']))
			{
				$relatedPosition = $theme->getCfg('product_page/related_position');
				//TODO:remove: $relatedPosition = 11;
				switch ($relatedPosition)
				{
					case 10:
						$p['secondaryCol'][0] = $section['related'];
						break;
					case 11:
						$p['secondaryCol'][1] = $section['related'];
						break;
					case 20:
						$p['collatSecondaryCol'] = $section['related'];
						break;
				}
			}
			
			
			
			//Width (in grid units) of product page sections
			$imgColUnits					= $theme->getCfg('product_page/image_column');
			$primaryColUnits				= $theme->getCfg('product_page/primary_column');
			$secondaryColUnits				= $theme->getCfg('product_page/secondary_column');
			$container2ColUnits				= $imgColUnits + $primaryColUnits;
			$collatPrimaryColUnits			= $imgColUnits + $primaryColUnits;
			$collatSecondaryColUnits		= $secondaryColUnits;

			//If no secondary column
			if (empty($secondaryColUnits))
			{
				$primaryColUnits			+= 12 - ($imgColUnits + $primaryColUnits);
				$container2ColUnits			= $imgColUnits + $primaryColUnits;
				$collatPrimaryColUnits		= 9;
				$collatSecondaryColUnits	= 3;
			}
			
			//If no related products, stretch collateral primary column
			if (!isset($section['related']))
			{
				$container2ColUnits			= 12;
				$collatPrimaryColUnits		= 12;
				$collatSecondaryColUnits	= 0;
			}
			elseif (!isset($p['secondaryCol']))
			{
				$container2ColUnits 		= 12;
			}

			//Grid classes
			$imgColGridClass				= 'grid12-' . $imgColUnits;
			$primaryColGridClass			= 'grid12-' . $primaryColUnits;
			$secondaryColGridClass			= 'grid12-' . $secondaryColUnits;
			$container2ColGridClass			= 'grid12-' . $container2ColUnits;
			$collatPrimaryColGridClass		= 'grid12-' . $collatPrimaryColUnits;
			$collatSecondaryColGridClass	= 'grid12-' . $collatSecondaryColUnits;
			if (empty($secondaryColUnits))
			{
				$secondaryColGridClass	= '';
			}
		?>

        <div class="product-img-column <?php echo $imgColGridClass; ?>">
            <?php echo $this->getChildHtml('media') ?>
            <?php //Product labels
				echo $this->helper('ultimo/labels')->getLabels($_product);
			?>
        </div>
        
        <div class="product-shop <?php echo $primaryColGridClass; ?>">

            <div class="product-name">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
            </div>
            
            <?php echo $this->getReviewsSummaryHtml($_product, false, true); //reviews ?>
            
            <?php if ($_product->getShortDescription()): ?>
                <div class="short-description">
                    <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                </div>
            <?php endif;?>

            <?php if ($theme->getCfg('product_page/sku')): ?>
                <div class="sku"><span><?php echo $this->__('SKU'); ?>: </span><?php echo $_product->getSku(); ?></div>
            <?php endif; ?>

            <?php echo $this->getChildHtml('alert_urls'); //alerts ?>
            
            <?php if ($extrahint_html = $this->getChildHtml('extrahint')): //qty increments ?>
                <div class="extrahint-wrapper"><?php echo $extrahint_html; ?></div>
            <?php endif; ?>
            
            <div class="product-type-data<?php echo $productTypeClasses; ?>"><?php echo $this->getChildHtml('product_type_data'); ?></div>
            
            <?php echo $this->getTierPriceHtml(); //tier prices ?>

            <?php if (!$this->hasOptions()): //add to cart when no options ?>
                <?php if($_product->isSaleable()): ?>
                    <div class="add-to-box">
                        <?php echo $this->getChildHtml('addtocart') ?>
                    </div>
                <?php endif; ?>
                <?php echo $this->getChildHtml('extra_buttons') ?>
            <?php endif; ?>

            <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
                <?php if ($container1_html = $this->getChildChildHtml('container1', '', true, true)): ?>
                    <div class="container1-wrapper"><?php echo $container1_html; ?></div>
                <?php endif; ?>
            <?php endif;?>
            
            <?php if ($addtoLinksHtml = $this->getChildHtml('addto')): //compare, wishlist, to friend ?>
                <div class="action-box clearer">
					<?php echo $addtoLinksHtml; ?>
				</div>
            <?php endif; ?>
            
            <?php echo $this->getChildHtml('other'); ?>

            <?php if ($tmpHtml = $this->getChildHtml('block_product_primary_bottom')): ?>
            	<div class="feature-wrapper top-border block_product_primary_bottom"><?php echo $tmpHtml; ?></div>
            <?php endif; ?>
            
            <?php if ($tmpHtml = $this->getChildHtml('product_primary_bottom_placeholder')): //Placeholder for extensions ?>
            	<div class="feature-wrapper top-border"><?php echo $tmpHtml; ?></div>
            <?php endif; ?>

        </div> <!-- end: product-shop -->
        
        <?php if ($secondaryColUnits): //(!empty($secondaryColUnits)): ?>
            <div class="product-secondary-column <?php echo $secondaryColGridClass; ?> custom-sidebar-right">
            	<div class="inner">

					<?php //Placeholder for extensions ?>
					<?php if ($tmpHtml = $this->getChildHtml('product_secondary_top_placeholder')): //Placeholder for extensions ?>
						<div class="margin-bottom"><?php echo $tmpHtml; ?></div>
                    <?php endif; ?>
                    
                    <?php if (isset($p['secondaryCol'][0])): ?>
						<?php echo $p['secondaryCol'][0]; ?>
                    <?php endif; ?>
                    
                    <?php if ($tmpHtml = $this->getChildHtml('block_product_secondary_bottom')): ?>
                        <div class="feature-wrapper top-border block_product_secondary_bottom"><?php echo $tmpHtml; ?></div>
                    <?php endif; ?>
                    
                    <?php if (isset($p['secondaryCol'][1])): ?>
						<div class="margin-top"><?php echo $p['secondaryCol'][1]; ?></div>
                    <?php endif; ?>
                    
                    <?php /*?>
					<?php if (isset($section['related'])): ?>
                    	<div class="margin-top"><?php echo $section['related']; ?></div>
                    <?php endif; ?>
                    <?php */?>

				</div>
            </div> <!-- end: product-secondary-column -->
        <?php endif; ?>

        <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
			<?php if ($container2_html = $this->getChildChildHtml('container2', '', true, true)): ?>
        		<div class="box-additional <?php echo $container2ColGridClass; ?>">
					<div class="container2-wrapper"><?php echo $container2_html; ?></div>
				</div>
        	<?php endif; ?>
        <?php endif; ?>

    </form>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    
	<div class="box-additional box-tabs <?php echo $collatPrimaryColGridClass; ?>">
    	<?php $info_tabs_html = trim($this->getChildHtml('info_tabs'));
			if ($info_tabs_html) echo $info_tabs_html; ?>

		<?php //Open the "Reviews" tab, when "X Review(s)" or "Be the first to review this product" links are clicked ?>
		<script type="text/javascript">
		//<![CDATA[
			jQuery(function($){$("#goto-reviews, #goto-reviews-form").click(function(){if($("#product-tabs").hasClass("accor")){$("#product-tabs .tabs-panels").data("tabs").click($(".tabs-panels .acctab").index($("#acctab-tabreviews")))}else{$("#product-tabs .tabs").data("tabs").click($("#tab-tabreviews").index())}})});
		//]]>
		</script>
        
        <?php echo $this->getChildHtml('product_additional_data') ?>
	</div> <!-- end: box-tabs -->
    
    
    
    <?php if (isset($p['collatSecondaryCol'])): ?>
		<div class="box-additional box-sidebar custom-sidebar-right <?php echo $collatSecondaryColGridClass; ?>">
			<div class="inner"><?php echo $p['collatSecondaryCol']; ?></div>
		</div>
	<?php endif; ?>
         
    <?php if (isset($section['upsell'])): ?>
    	<div class="box-additional box-up-sell <?php echo $collatPrimaryColGridClass; ?>"><?php echo $section['upsell']; ?></div>
    <?php endif; ?>
    
</div> <!-- end: product-view -->

</div> <!-- end: product_view_container -->
