<script>
    window.addEventListener('load', function () {
        var loadScreen = document.getElementById('load-screen');
        document.body.removeChild(loadScreen);
    });
</script>
<div id="load-screen">
    <div style="position: fixed; top: 0; z-index: 10; width: 100%; height: 100%; background: #000 url('<?php echo $this->getSkinUrl(''); ?>/images/infortis/_shared/colorbox/overlay.png'); opacity: 0.5;"></div>
    <div style=" position: absolute; left: 50%; top: 50%; z-index: 20; margin: -20px 0 0 -20px; border-radius: 5px; width: 40px; height: 40px; background: #000 url('<?php echo $this->getSkinUrl(''); ?>/images/loading.gif') no-repeat center;"></div>
</div>