<?php
// Define labels black and white 
$black = array(
    "african safari", "art for kids", "art for him", 
    "modern blooms", "say it with words", "shabby chic", 
    "the real marilyn", "antonio massa",
    "cuisine", "dance", "fashion", "music", 
    "people", "sports & recreation", 
    "still life", "transportation");
?>
<div class="category-products">
<?php
	$_helper    = $this->helper('catalog/output');
        
        if (!Mage::registry('current_category')) {
            return;
        }

$_category = $this->getCurrentCategory();
?>
    <div class="page-title category-title-top">
        <h1><?php echo $this->escapeHtml($_category->getName()) ?></h1>
    </div>
<?php
$_categories = $_category->getCollection();
$_categories->addAttributeToSelect('url_key')
    ->addAttributeToSelect('name')
    ->addAttributeToSelect('all_children')
    ->addAttributeToSelect('is_anchor')
    ->addAttributeToFilter('is_active', 1)
    ->addIdFilter($_category->getChildren())
    ->setOrder('position', Varien_Db_Select::SQL_ASC)
    ->load();
?>
<?php $_count = is_array($_categories)?count($_categories):$_categories->count();?>

<?php if($_count): ?>
    <div class="create-art-list-container">
        <div class="create-art-list category-collections">

    <?php 
        $_columnCount = $this->getColumnCount();/*'4'*/  
        $count = 0;
        foreach ($_categories as $k => $_category):
            $firstItemSku = $_category->getProductCollection()->getFirstItem()->getSku();
            $categoryImg = $_helper->getAmazonS3CategoryUrl() .$firstItemSku . '.jpg';
            $anchor = $this->getCategoryUrl($_category); 
            $categoryName = $_category->getName(); 
            $categoryImg = Mage::getModel('catalog/category')->load($k)->getCollectionImageUrl(); 
            $catVar = $_helper->categoryAttribute($_category, $_category->getName(), 'name');
            if(!empty($categoryImg)): ?>
                
                <div class="category-isotope">
                    <a href="<?php echo $anchor; ?>" title="<?php echo $categoryName; ?>">
                        <div class="overlay-opacity"></div>
                        <div class="overlay-icon"></div>
                        <div class="overlay-info <?php if(in_array(strtolower(trim($catVar)), $black)) echo "black"?>"><?php echo $categoryName; ?></div>
                        <img class="image-isotope" src="<?php echo $categoryImg; ?>" title="<?php echo $categoryName; ?>" alt="<?php echo $categoryName; ?>" />
                    </a>
                </div>
            
            <?php endif; ?>
    <?php $count++; ?>
    <?php endforeach; ?>
        </div>
    </div>
    <div class="clear"></div>
<?php endif; ?>
    <script>
        jQuery(document).ready(function () {
            var itemSizes = [
                [580, 250], [580, 400], [580, 400], [580, 250],
                [580, 250], [285, 250], [285, 250],
                [285, 250], [285, 250], [580, 250],
                [580, 500], [580, 245], [580, 245],
                [580, 245], [580, 500], [580, 245],
                [580, 500], [580, 245], [580, 245]
            ];
            var $container = jQuery('.category-collections');

            $container.find(".image-isotope").each(function (index) {
                var i = index % itemSizes.length;

                jQuery(this).width(itemSizes[i][0]);
                jQuery(this).height(itemSizes[i][1]);
            });

            $container.isotope({
                itemSelector: '.category-isotope',
                layoutMode: 'masonry',
                masonry: {
                    columnWidth: 1
                }
            });
        });
    </script>
</div>