            <div class="content-header-block">
              <div class="bmb-logo"><a href="javascript:void(0);"><img src="<?php echo $this->getSkinUrl('bmbleb/images/bmb-ctl.png'); ?>" alt="bmbleb logo" /></a></div>
              <div class="header-content">
                <h2>Please login or register for a free bmbleb account</h2>
               </div>
            </div>
            <style type="text/css">

div.form-wrap { width:48%; float:left; margin-top:20px; margin-right:20px; }
div.form-wrap.last { margin-right:0; }

div.form-wrap .form-list td.value input.input-text { width:90%; }
div.form-wrap .form-list td.label label { width:125px; padding-right:10px; } 
/* more adjustments - move these all to css */

/* override some default boxes backgrounds */
.entry-edit .entry-edit-head { background:none; }
.entry-edit fieldset, .entry-edit .fieldset { background:none; border:none; }

div.form-wrap div.content-header { display:none; }
.form-wrap .content-footer { padding-left:80px; }
#login-register-wrapper .form-buttons { padding-left:0px; }
#login-register-wrapper .forgot-pwd { padding-left:80px; }

/*
! working on table cell problem
this works in ffox and chrome but not IE 9 or IE compat
 */
#login-register-wrapper td { display: table-row; }
#login-register-wrapper td.value input.input-text { margin-bottom:10px; }


</style>

