<?php /* @var $this Socketware_Bmbleb_Block_Adminhtml_Login */ ?>
<div id="sb-login-register-wrapper">
            <div class="content-header-block">
              <div class="bmb-logo"><a href="www.springbot.com"><img align=left width=60 height=60 src="<?php echo $this->getSkinUrl('bmbleb/images/springbot-ctl.png'); ?>" alt="springbot logo" />&nbsp;</a>
			     <h2>Springbot Account Login</h2>
			 </div>
              <div class="header-content">
                <p>Our Marketing Magic uncovers hard-to-find social and demographic data about your customers.</p>
              </div>
            </div>
		
    <div style="background:#F9F9F9 url(skin/adminhtml/base/default/bmbleb/images/registration-bg.png) no-repeat left top;">
    	<?php echo $this->getChildHtml('form'); ?>
    </div>
</div>
