<div class="j-content">
<div class="j-box-left box2">
		<a href="<?php echo 'http://app.springbot.com/dashboard'; ?>" target="_blank">
		<img align=left  src="<?php echo $this->getSkinUrl('bmbleb/images/plugin_dashboard_syncing.jpg'); ?>" alt="springbot logo" />
		</a>
	</div>
</div>
<div class="tc-info">
	<p class="tc-link"><a href="http://www.springbot.com/content/terms_of_use" target="_blank" title="Terms &amp; Conditions">View our Terms &amp; Conditions</a></p>
	<p style="float:right;">Springbot v<?php echo Mage::getConfig()->getModuleConfig("Springbot_Combine")->version ?></p>
</div>

