<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<?php if ($post): ?>
	<?php $helper = $this->helper('wordpress') ?>
	<?php $author = $post->getAuthor() ?>
	<div class="post-view">
            <!--JP: Ticket 125 - remove blog title-->
            <!--<h1 class="blog-title">Blog</h1>-->
		<?php echo $this->getBeforePostContentHtml() ?>
		<div class="post-entry entry std<?php if ($post->getFeaturedImage()): ?> post-entry-with-image<?php endif; ?>">
			<?php if ($post->isViewableForVisitor()): ?>
				<?php if ($featuredImage = $post->getFeaturedImage()): ?>
					<!--<div class="featured-image left">
                                                <img src="<?php echo $featuredImage->getAvailableImage() ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/>
                                            </div>-->
				<?php endif; ?>
                <!--JP: Ticket 125 - remove post data-->
                <!--<p class="post-date when"><?php //echo stripslashes($this->__('This entry was posted on %s<span class=\"by-author\"> by %s</span>.', $post->getPostDate(), $post->getAuthor()->getDisplayName())) ?></p>-->

                <div class="page-title post-title">
                    <h1><?php echo $this->escapeHtml($post->getPostTitle()) ?></h1>
                </div>
				<?php echo $post->getPostContent() ?>
				<div>
					<!-- active buttons sharethis-->
					<?php echo Mage::helper('wordpress/social')->getButtons($post) ?>

					<script>
						jQuery(document).ready(function(){
							var checkExistTwitter = setInterval(function() {
								if (jQuery('.st_twitter span span').length) {
									console.log("Exists twi!");
									jQuery('.st_twitter span span').removeClass('chicklets').addClass('icon icon-hover i-twitter-w');
									clearInterval(checkExistTwitter);
								}
							}, 100);
							var checkExistFacebook = setInterval(function() {
								if (jQuery('.st_facebook span span').length) {
									console.log("Exists face!");
									jQuery('.st_facebook span span').removeClass('chicklets').addClass('icon icon-hover i-facebook-w');
									clearInterval(checkExistFacebook);
								}
							}, 100);
							var checkExistPinterest = setInterval(function() {
								if (jQuery('.st_pinterest span span').length) {
									console.log("Exists pin!");
									jQuery('.st_pinterest span span').removeClass('chicklets').addClass('icon icon-hover i-pinterest-w');
									clearInterval(checkExistPinterest);
								}
							}, 100);

						});
					</script>
					<!-- active buttons sharethis-->
				</div>
			<?php else: ?>
				<?php echo $this->getPasswordProtectHtml() ?>
			<?php endif; ?>
		</div>
		<?php //echo $this->getAfterPostContentHtml() ?>
		<?php //echo $this->getCommentsHtml() ?>
	</div>
<?php endif; ?>