<?php
    $helpImg = $helpImg = $this->helper('infortis/image');
    //$helpRelated = $this->helper('onetree_relatedproducts/data');
?>
<div>
    <?php if($this->showProductsSameCategory()):?>
    <div class="related_products">
        <h4><?php echo $this->__('From the same category') ?></h4><!-- add translate -->
    </div>
    <div id="same-category" class="owl-carousel owl-theme">
        <?php foreach($this->getProductsSameCategory() as $product): ?>
            <div class="item" style="width: <?php echo $this->getImageWidth()?>px; height: <?php echo $this->getImageHeight()?>px;"><a href="<?php echo $product->getProductUrl() ?>"><img src="<?php echo $helpImg->getImg($product, 0, 0, 'thumbnail');?>" alt="Owl Image"></a></div>
        <?php endforeach;?>
    </div>
    <?php endif; ?>

    <?php if($this->showProductsSameArtist()): ?>
    <div class="related_products">
        <h4><?php echo $this->__('From the same artist') ?></h4> <!-- add translate-->
    </div>
    <div id="owl-demo" class="owl-carousel owl-theme">
        <?php foreach($this->getProductsSameArtist() as $product): ?>
            <div class="item" style="width: <?php echo $this->getImageWidth()?>px; height: <?php echo $this->getImageHeight()?>px;"><a href="<?php echo $product->getProductUrl() ?>"><img src="<?php echo $helpImg->getImg($product, 0, 0, 'thumbnail');?>" alt="Owl Image"></a></div>
        <?php endforeach;?>
    </div>
    <?php endif; ?>
</div>

<script>
    jQuery(document).ready(function(){

        jQuery("#same-category,#owl-demo").owlCarousel({
                autoPlay: <?php echo $this->getAutoPlay()?>,
                items:<?php echo $this->getItemsPerPage() ?>,
                itemsMobile : [479,<?php echo $this->getItemsPerPageMobile() ?>],
                itemsScaleUp:true,
                stopOnHover:true
            }
        );
    })
</script>

/*

*/

