<?php
    $helpImg = $helpImg = $this->helper('infortis/image');
    $category = $this->getCategory();
    //$helpRelated = $this->helper('onetree_relatedproducts/data');
?>
<div>
    <?php //print_r($this->getProductsSameCategory())?>
    <?php if($this->showProductsSameCategory()):?>
        <?php if( null !== $this->getProductsSameCategory() && $this->getProductsSameCategory()->count() > 0 && $this->getArtist()->getId() != $this->getCurrentCategory()->getId()): ?>
            <div class="related_products">
                <h4><a href="<?php echo $this->getCategory()->getUrl() ?>"><?php echo $this->__('More in ').$this->getCategory()->getName() ?></a></h4>
            </div>
            <div id="same-category" class="owl-carousel owl-theme">
                <?php foreach($this->getProductsSameCategory() as $product):

                    $_product_rel = Mage::getModel('catalog/product')->load($product->getId());
                    $name_artist = $_product_rel->getUdfArtistName();
                    $name_picture = $_product_rel->getName();

                    $canvas_available = $_product_rel->getUdfCanvas();
                    $poster_available = $_product_rel->getUdfPoster();
                    $paper_available = $_product_rel->getUdfPhotoPaper();

                    $details = '';
                    $unique = 0;

                    if($canvas_available){
                        $details = $details.' canvas';
                        $unique = $unique +1;
                    }
                    if($poster_available){
                        if($unique > 0){
                            $details = $details.' and poster';
                        }else{
                            $details = $details.' poster';
                        }

                    }
                    if($paper_available){
                        if($unique > 0){
                            $details = $details.' and paper';
                        }else{
                            $details = $details.' paper';
                        }
                    }
                    $categories = '';
                    $categoryIds = $_product_rel->getCategoryIds();

                    if(count($categoryIds) ){
                        foreach ($categoryIds as $category_id) {
                            $_cat = Mage::getModel('catalog/category')->load($category_id);
                            if($_cat->getName() != $name_artist){
                                $categories = $categories .' '. $_cat->getName();
                            }

                        }

                    }
                    ?>
                    <div class="item" style="width: <?php echo $this->getImageWidth()?>px; height: <?php echo $this->getImageHeight()?>px;">
                        <a href="<?php echo $product->getProductUrl() ?>">
                            <img src="<?php echo $helpImg->getImg($product, 0, 0, 'thumbnail');?>"
                                 alt="<?php echo $name_artist.' | '.$categories.' | '.$details.' | '.$name_picture ?>">
                        </a>
                    </div>
                <?php endforeach;?>
            </div>
        <?php endif; ?>
    <?php endif; ?>

    <?php if($this->showProductsSameArtist()): ?>
        <?php if( null !== $this->getProductsSameArtist() && $this->getProductsSameArtist()->count() > 0): ?>
            <div class="related_products">
                <h4><a class="" href="<?php echo $this->getArtist()->getUrl() ?>"><?php echo $this->__('More from ').$this->getArtist()->getName() ?></a></h4>
            </div>
            <div id="owl-demo" class="owl-carousel owl-theme">
                <?php foreach($this->getProductsSameArtist() as $product):
                    $_product_rel2 = Mage::getModel('catalog/product')->load($product->getId());
                    $name_artist = $_product_rel2->getUdfArtistName();
                    $name_picture = $_product_rel2->getName();

                    $canvas_available = $_product_rel2->getUdfCanvas();
                    $poster_available = $_product_rel2->getUdfPoster();
                    $paper_available = $_product_rel2->getUdfPhotoPaper();

                    $details = '';
                    $unique = 0;

                    if($canvas_available){
                        $details = $details.' canvas';
                        $unique = $unique +1;
                    }
                    if($poster_available){
                        if($unique > 0){
                            $details = $details.' and poster';
                        }else{
                            $details = $details.' poster';
                        }

                    }
                    if($paper_available){
                        if($unique > 0){
                            $details = $details.' and paper';
                        }else{
                            $details = $details.' paper';
                        }
                    }
                    $categories = '';
                    $categoryIds = $_product_rel2->getCategoryIds();

                    if(count($categoryIds) ){
                        foreach ($categoryIds as $category_id) {
                            $_cat = Mage::getModel('catalog/category')->load($category_id);
                            if($_cat->getName() != $name_artist){
                                $categories = $categories .' '. $_cat->getName();
                            }

                        }

                    }
                    ?>
                    <div class="item" style="width: <?php echo $this->getImageWidth()?>px; height: <?php echo $this->getImageHeight()?>px;">
                        <a href="<?php echo $product->getProductUrl() ?>">
                            <img src="<?php echo $helpImg->getImg($product, 0, 0, 'thumbnail');?>"
                                 alt="<?php echo $name_artist.' | '.$categories.' | '.$details.' | '.$name_picture ?>">
                        </a>
                    </div>
                <?php endforeach;?>
            </div>
        <?php endif;?>
    <?php endif; ?>
</div>

<script>
    jQuery(document).ready(function(){

        jQuery("#same-category,#owl-demo").owlCarousel({
                autoPlay: <?php echo $this->getAutoPlay()?>,
                items:<?php echo $this->getItemsPerPage() ?>,
                itemsMobile : [479,<?php echo $this->getItemsPerPageMobile() ?>],
                itemsScaleUp:true,
                stopOnHover:true
            }
        );
    })
</script>

/*

*/

