<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<div class="category-collections">
    <div>
        <div class="category-description std ">
            Get Inspired            
        </div>
    </div>
</div>
<div class="blog-content">
    <?php
    //echo "<pre>";
    //var_dump($this);
    //echo "</pre>";
    ?>
    <?php echo $this->getPostListHtml() ?>
</div>

<?php /* <div class="blog-cust-category">
  <img src="<?php echo $this->getSkinUrl('images/blog-demo.jpg');?>" alt="" class="blog-cust-arrow">
  <div class="blog-cust-logo">
  <span class="blog-cust-more">+</span>
  <span class="blog-cust-text">Read more</span>
  </div>
  </div><div class="blog-cust-category">
  <img src="<?php echo $this->getSkinUrl('images/blog-demo.jpg');?>" alt="" class="blog-cust-arrow">
  <div class="blog-cust-logo">
  <span class="blog-cust-more">+</span>
  <span class="blog-cust-text">Read more</span>
  </div>
  </div><div class="blog-cust-category">
  <img src="<?php echo $this->getSkinUrl('images/blog-demo.jpg');?>" alt="" class="blog-cust-arrow">
  <div class="blog-cust-logo">
  <span class="blog-cust-more">+</span>
  <span class="blog-cust-text">Read more</span>
  </div>
  </div><div class="blog-cust-category">
  <img src="<?php echo $this->getSkinUrl('images/blog-demo.jpg');?>" alt="" class="blog-cust-arrow">
  <div class="blog-cust-logo">
  <span class="blog-cust-more">+</span>
  <span class="blog-cust-text">Read more</span>
  </div>
  </div> */ ?>
